ДЗ 2. 
- реализовать tfidf для quora.txt
- Для BoW, TF-IDF и датасета quora.txt - найти самые схожие объекты (косинусное расстояние)
- Классная работа из занятий 1 и 2


# Реализовать tfidf для quora.txt

In [1]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

--2022-12-08 13:16:03--  https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/obaitrix9jyu84r/quora.txt [following]
--2022-12-08 13:16:03--  https://www.dropbox.com/s/dl/obaitrix9jyu84r/quora.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucb41a649660e4c684ab1b831b71.dl.dropboxusercontent.com/cd/0/get/ByNA4Gdf0t-4hQMb-9LwgwTvCMk5iEWFNyXW_kTKIky3QKKF8VASWTYBTGmfCApidZzyJICIKgUdE9smzv-fS-1V0HfqIP7f5CvZXE5-ps5zxyHckvlkt269sux3rVzO-WUOZkpn_WKK6Wfk6CSuKTFd40iSWkYhdH86Etg_j8dAAQ/file?dl=1# [following]
--2022-12-08 13:16:03--  https://ucb41a649660e4c684ab1b831b71.dl.dropboxusercontent.com/cd/0/get/ByNA4Gdf0t-4hQMb-9LwgwTvCMk5iEWFNyXW_kTKIky3QKKF8VASWTYBTGmfCApidZzyJICIKgUdE9smzv-fS-1

In [1]:
data = list(open("./quora.txt", encoding="utf-8"))
data[]

"What TV shows or books help you read people's body language?\n"

In [2]:
len(data)

537272

In [3]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
#using the count vectorizer
text = data[1000:1200]
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

  (0, 953)	1
  (0, 482)	1
  (0, 859)	1
  (0, 726)	1
  (0, 611)	1
  (0, 134)	1
  (0, 610)	1
  (0, 457)	1
  (0, 461)	1
  (1, 953)	1
  (1, 482)	1
  (1, 859)	1
  (1, 457)	1
  (1, 108)	1
  (1, 943)	1
  (1, 876)	1
  (1, 831)	1
  (1, 735)	1
  (1, 833)	2
  (1, 356)	1
  (1, 669)	1
  (1, 728)	1
  (2, 953)	1
  (2, 859)	1
  (2, 955)	1
  :	:
  (198, 570)	1
  (198, 36)	1
  (198, 780)	1
  (198, 83)	1
  (198, 781)	1
  (198, 400)	1
  (198, 981)	1
  (198, 338)	1
  (198, 434)	1
  (198, 403)	1
  (198, 631)	1
  (198, 500)	1
  (198, 402)	1
  (198, 862)	1
  (199, 859)	2
  (199, 457)	2
  (199, 622)	1
  (199, 260)	1
  (199, 961)	1
  (199, 604)	1
  (199, 140)	1
  (199, 114)	1
  (199, 172)	1
  (199, 573)	1
  (199, 311)	1


In [42]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [43]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [44]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])

idf_weights
the           1.814669
what          1.985817
is            1.985817
to            2.333013
how           2.371479
...                ...
forget        5.610158
formed        5.610158
fractured     5.610158
fittings      5.610158
zero          5.610158

[989 rows x 1 columns]

In [45]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
sugar       0.628818
regular     0.314409
substitute  0.314409
powdered    0.314409
recipe      0.314409
...              ...
fast        0.000000
fats        0.000000
favorite    0.000000
fear        0.000000
zero        0.000000

[989 rows x 1 columns]

# Для BoW, TF-IDF и датасета quora.txt - найти самые схожие объекты (косинусное расстояние)

# Bag Of Words (BOW)

In [46]:
def vectorize(tokens):
    ''' This function takes list of words in a sentence as input 
    and returns a vector of size of filtered_vocab.It puts 0 if the 
    word is not present in tokens and count of token if present.'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    '''This functions returns a list in which the order remains 
    same and no item repeats.Using the set() function does not 
    preserve the original ordering,so i didnt use that instead'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]

#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","is","a"]

#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]


In [47]:
all_words = []
for i in text:
    for j in i.lower().split():
        all_words.append(j)
print(all_words)

['what', 'is', 'the', 'reason', 'of', 'british', 'occupation', 'in', 'india?', 'what', 'is', 'the', 'best', 'way', 'to', 'substitute', 'regular', 'sugar', 'for', 'powdered', 'sugar', 'in', 'a', 'recipe?', 'when', 'they', 'made', 'the', 'first', 'clock,', 'how', 'did', 'they', 'know', 'what', 'time', 'it', 'was?', 'how', 'did', 'they', 'set', 'it?', 'should', 'i', 'start', 'preparing', 'for', 'the', 'iit', 'jee', 'in', 'class', '10', 'only?', 'as', 'a', 'cricket', 'fan,', 'who', 'do', 'you', 'think', 'will', 'win', 'the', 'world', 'cup?', 'why', 'would', "ra's", 'al', 'ghul', 'want', 'to', 'go', 'to', 'war', 'with', "batman's", 'enemies?', 'do', 'you', 'personally', 'believe', 'hillary', 'clinton', 'has', 'committed', 'voter', 'fraud?', 'who', 'are', 'the', 'best', 'girls', 'on', 'snapchat?', 'why', 'has', 'not', 'nasa', 'or', 'other', 'countries', 'sent', 'human', 'to', 'the', 'moon', 'again?', 'how', 'do', 'i', 'join', 'the', 'russian', 'military', 'if', "i'm", 'an', 'american', 'citi

In [48]:
vocab=unique(all_words)
print(vocab)
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)
print(filtered_vocab)

#convert sentences into vectords
print(text[0])
vector1=vectorize(text[0])
print(vector1)
print(text[1])
vector2=vectorize(text[1])
print(vector2)

['what', 'is', 'the', 'reason', 'of', 'british', 'occupation', 'in', 'india?', 'best', 'way', 'to', 'substitute', 'regular', 'sugar', 'for', 'powdered', 'a', 'recipe?', 'when', 'they', 'made', 'first', 'clock,', 'how', 'did', 'know', 'time', 'it', 'was?', 'set', 'it?', 'should', 'i', 'start', 'preparing', 'iit', 'jee', 'class', '10', 'only?', 'as', 'cricket', 'fan,', 'who', 'do', 'you', 'think', 'will', 'win', 'world', 'cup?', 'why', 'would', "ra's", 'al', 'ghul', 'want', 'go', 'war', 'with', "batman's", 'enemies?', 'personally', 'believe', 'hillary', 'clinton', 'has', 'committed', 'voter', 'fraud?', 'are', 'girls', 'on', 'snapchat?', 'not', 'nasa', 'or', 'other', 'countries', 'sent', 'human', 'moon', 'again?', 'join', 'russian', 'military', 'if', "i'm", 'an', 'american', 'citizen?', 'get', 'degree', 'after', 'diploma', 'mechanical', 'engineering', 'while', 'working', 'powerplant?', 'individuals', 'and', 'events', 'history', 'source', 'pride', 'mauritius?', 'was', 'production', 'artwor

# Находим самые схожие объекты через косинусное растояние (BoW)

In [49]:
v_array = []
for i in text:
    v_array.append(vectorize(i.lower().split()))
print(v_array)

[[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [53]:
from numpy import dot
from numpy.linalg import norm

cos = dict()
for i, a in enumerate(v_array):
    for j, b in enumerate(v_array):
        if i != j : 
            cos_sim = dot(a, b)/(norm(a)*norm(b))
            cos[(i,j)] = cos_sim
pair = None
print(max(cos.values()))   
for x in cos:
    if cos.get(x) == max(cos.values()):
        print(x)
        pair = x
        break
for x in pair:
    print(text[x])

0.5976143046671968
(66, 80)
How can I improve my social english/ english conversation skills?

How can I enhance my English translation?



# Находим самые схожие объекты через косинусное растояние (TF-IDF)

In [51]:
v_array_tfidf = tf_idf_vector.toarray()

In [54]:
cos = dict()
for i, a in enumerate(v_array_tfidf):
    for j, b in enumerate(v_array_tfidf):
        if i != j : 
            cos_sim = dot(a, b)/(norm(a)*norm(b))
            cos[(i,j)] = cos_sim
pair = None
print(max(cos.values()))   
for x in cos:
    if cos.get(x) == max(cos.values()):
        print(x)
        pair = x
        break
for x in pair:
    print(text[x])

0.4331584295768895
(127, 152)
What's the difference between a professor and a teacher?

What is the difference between the two sentences with "of" and "for"?

